"""alter_whatsapp_preference_default

Revision ID: 2fcff837b64e
Revises: 52a070d8d2a1
Create Date: 2026-06-18 10:30:54.375056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcff837b64e'
down_revision: Union[str, Sequence[str], None] = '52a070d8d2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notification_preferences', 'pref_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.execute("UPDATE user_notification_preferences SET pref_whatsapp = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notification_preferences', 'pref_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
