"""add_notifications_preferences_and_configs

Revision ID: 52a070d8d2a1
Revises: a1b2c3d4e5f9
Create Date: 2026-06-17 11:29:55.710092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52a070d8d2a1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=True),
    sa.Column('target_permission', sa.String(length=50), nullable=True),
    sa.Column('recipient_user_ids', sa.Text(), nullable=True),
    sa.Column('dynamic_role', sa.String(length=50), nullable=True),
    sa.Column('channels', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_in_app', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('pref_desktop', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pref_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pref_whatsapp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index(op.f('uq_fields_code_per_form'), table_name='fields', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_fields_code_per_form', 'fields', ['form_id', 'field_code'])
    op.drop_constraint(op.f('uq_report_template_code'), 'report_templates', type_='unique')
    op.create_index('uq_report_template_code', 'report_templates', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.alter_column('workbook_site_submitters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workbook_sites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workbooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workbooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_workbooks_is_active'), table_name='workbooks')
    op.drop_index(op.f('idx_workbooks_workflow_id'), table_name='workbooks')
    op.drop_index(op.f('uq_wf_level_order'), table_name='workflow_levels', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_wf_level_order', 'workflow_levels', ['workflow_version_id', 'level_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wf_level_order', 'workflow_levels', type_='unique')
    op.create_index(op.f('uq_wf_level_order'), 'workflow_levels', ['workflow_version_id', 'level_number'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_workbooks_workflow_id'), 'workbooks', ['workflow_id'], unique=False)
    op.create_index(op.f('idx_workbooks_is_active'), 'workbooks', ['is_active'], unique=False)
    op.alter_column('workbooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('workbooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('workbook_sites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('workbook_site_submitters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('uq_report_template_code', table_name='report_templates', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_report_template_code'), 'report_templates', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_fields_code_per_form', 'fields', type_='unique')
    op.create_index(op.f('uq_fields_code_per_form'), 'fields', ['form_id', 'field_code'], unique=True, postgresql_where='(is_deleted = false)')
    op.drop_table('user_notification_preferences')
    op.drop_table('notification_configs')
    # ### end Alembic commands ###
