"""Field soft-delete unique constraint

Revision ID: 668b2e9d1d97
Revises: b9933d1a4d8a
Create Date: 2026-06-05 12:59:36.361080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668b2e9d1d97'
down_revision: Union[str, Sequence[str], None] = 'b9933d1a4d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_fields_code_per_form'), 'fields', type_='unique')
    op.create_index('uq_fields_code_per_form', 'fields', ['form_id', 'field_code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_fields_code_per_form', table_name='fields', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_fields_code_per_form'), 'fields', ['form_id', 'field_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
