"""Soft delete for FieldVersion

Revision ID: b9933d1a4d8a
Revises: 102cdbd1439c
Create Date: 2026-06-05 12:57:07.607204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9933d1a4d8a'
down_revision: Union[str, Sequence[str], None] = '102cdbd1439c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_versions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('field_versions', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('field_versions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('field_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('field_versions', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('field_versions', sa.Column('delete_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'field_versions', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'field_versions', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_versions', type_='foreignkey')
    op.drop_constraint(None, 'field_versions', type_='foreignkey')
    op.drop_column('field_versions', 'delete_reason')
    op.drop_column('field_versions', 'deleted_by')
    op.drop_column('field_versions', 'deleted_at')
    op.drop_column('field_versions', 'is_deleted')
    op.drop_column('field_versions', 'updated_by')
    op.drop_column('field_versions', 'updated_at')
    # ### end Alembic commands ###
